# Generated by Django 3.2.12 on 2025-12-19 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickzone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Skill_Level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='user',
            name='reserved_hours',
            field=models.IntegerField(default=0),
        ),
    ]
