# Generated by Django 3.2.12 on 2025-12-20 10:33

import django.core.validators
from django.db import migrations, models
import kickzone_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('kickzone_app', '0003_auto_20251219_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(validators=[kickzone_app.validators.SafeTextValidator(max_length=2000)]),
        ),
        migrations.AlterField(
            model_name='messagegroup',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[kickzone_app.validators.SafeTextValidator(max_length=500)]),
        ),
        migrations.AlterField(
            model_name='messagegroup',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Group name must be 2-255 characters with letters, numbers, spaces, hyphens, and underscores only.', regex='^[a-zA-Z0-9\\s\\-_]{2,255}$')]),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[kickzone_app.validators.SafeTextValidator(max_length=1000)]),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pitch_images/', validators=[kickzone_app.validators.ImageFileValidator(max_size_mb=5)]),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='location',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Location must be 5-255 characters with valid address format.', regex='^[a-zA-Z0-9\\s\\-_,.]{5,255}$')]),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must be 2-100 characters with letters, numbers, spaces, hyphens, and underscores only.', regex='^[a-zA-Z0-9\\s\\-_]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Size must be 2-50 characters with valid format.', regex='^[a-zA-Z0-9\\sx\\-]{2,50}$')]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[kickzone_app.validators.PromotionCodeValidator()]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[kickzone_app.validators.SafeTextValidator(max_length=500)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True, validators=[kickzone_app.validators.SafeTextValidator(max_length=500)]),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[kickzone_app.validators.SafeTextValidator(max_length=500)]),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Key must be 3-100 characters with letters, numbers, dots, and underscores only.', regex='^[a-zA-Z0-9_.]{3,100}$')]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[kickzone_app.validators.SafeTextValidator(max_length=1000)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must be 2-100 characters with letters, numbers, spaces, hyphens, and underscores only.', regex='^[a-zA-Z0-9\\s\\-_]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[kickzone_app.validators.PhoneNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Team name must be 2-100 characters with letters, numbers, spaces, hyphens, and underscores only.', regex='^[a-zA-Z0-9\\s\\-_]{2,100}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Position',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Position must be 2-50 letters and spaces only.', regex='^[a-zA-Z\\s]{2,50}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[kickzone_app.validators.PhoneNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[kickzone_app.validators.ImageFileValidator(max_size_mb=3)]),
        ),
    ]
